source 'https://rubygems.org'

gem 'eventmachine'
gem 'em-http-request'
gem 'em-hiredis'
gem 'thin'
gem 'http_router'
gem 'rack-async'
gem 'msgpack'
gem 'capistrano'
gem 'geoip'
gem 'useragent'
gem 'em-pg-client'
gem 'ipaddress'